server:
  port: 8000
spring:
  application:
    name: consul-consumer-order
  cloud:
    consul:
      host: 192.168.157.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}